import { useEffect, useState } from "react";
import { Helmet } from "react-helmet-async";
import DashboardLayout from "@/components/layouts/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useAuth } from "@/contexts/AuthContext";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { CreditCard, Download, Calendar, DollarSign, CheckCircle, Clock } from "lucide-react";
import { format } from "date-fns";

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

interface PayrollRecord {
  id: string;
  month: number;
  year: number;
  basic_salary: number;
  allowances: number;
  deductions: number;
  net_salary: number;
  status: string;
  paid_at: string | null;
  payment_mode: string | null;
}

const TeacherPayroll = () => {
  const { user, schoolId } = useAuth();
  const [teacherData, setTeacherData] = useState<any>(null);
  const [payroll, setPayroll] = useState<PayrollRecord[]>([]);
  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (user && schoolId) {
      fetchData();
    }
  }, [user, schoolId, selectedYear]);

  const fetchData = async () => {
    try {
      // Get teacher info
      const { data: teacher } = await supabase
        .from("teachers")
        .select("*")
        .eq("school_id", schoolId)
        .eq("user_id", user?.id)
        .single();

      // Get linked employee by email
      const { data: employee } = await supabase
        .from("employees")
        .select("id, base_salary, full_name, employee_code, bank_name, bank_account")
        .eq("school_id", schoolId)
        .eq("email", teacher?.email)
        .single();

      setTeacherData({ ...teacher, employees: employee });

      if (employee?.id) {
        // Get payroll records for selected year
        const { data: payrollData } = await supabase
          .from("payroll")
          .select("*")
          .eq("employee_id", employee.id)
          .eq("year", selectedYear)
          .order("month", { ascending: false });

        setPayroll(payrollData || []);
      }
    } catch (error) {
      console.error("Error fetching payroll:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPayslip = (record: PayrollRecord) => {
    // Generate a simple payslip
    const employee = teacherData?.employees;
    const payslipContent = `
PAYSLIP
=======
Employee: ${employee?.full_name || teacherData?.full_name}
Employee Code: ${employee?.employee_code || 'N/A'}
Period: ${MONTHS[record.month - 1]} ${record.year}

EARNINGS
--------
Basic Salary: ₹${record.basic_salary.toLocaleString()}
Allowances: ₹${record.allowances.toLocaleString()}

DEDUCTIONS
----------
Total Deductions: ₹${record.deductions.toLocaleString()}

NET PAY: ₹${record.net_salary.toLocaleString()}

Status: ${record.status === 'paid' ? 'PAID' : 'PENDING'}
${record.paid_at ? `Paid On: ${format(new Date(record.paid_at), 'dd MMM yyyy')}` : ''}
${record.payment_mode ? `Payment Mode: ${record.payment_mode}` : ''}

---
Generated by SkoolSetu
    `.trim();

    const blob = new Blob([payslipContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `payslip_${MONTHS[record.month - 1]}_${record.year}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
    
    toast.success("Payslip downloaded");
  };

  const totalEarnings = payroll.filter(p => p.status === 'paid').reduce((sum, p) => sum + p.net_salary, 0);
  const totalPending = payroll.filter(p => p.status === 'pending').reduce((sum, p) => sum + p.net_salary, 0);
  const paidMonths = payroll.filter(p => p.status === 'paid').length;

  if (loading) {
    return (
      <>
        <Helmet><title>My Payroll - SkoolSetu</title></Helmet>
        <DashboardLayout role="teacher">
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </DashboardLayout>
      </>
    );
  }

  return (
    <>
      <Helmet><title>My Payroll - SkoolSetu</title></Helmet>
      <DashboardLayout role="teacher">
        <div className="space-y-6">
          <div>
            <h1 className="text-2xl font-bold">My Payroll</h1>
            <p className="text-muted-foreground">View your salary and download payslips</p>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
            <Card className="shadow-card">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 rounded-lg bg-primary/10">
                    <DollarSign className="h-6 w-6 text-primary" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Base Salary</p>
                    <p className="text-2xl font-bold">₹{teacherData?.employees?.base_salary?.toLocaleString() || 0}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="shadow-card">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 rounded-lg bg-green-100">
                    <CheckCircle className="h-6 w-6 text-green-600" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Total Received ({selectedYear})</p>
                    <p className="text-2xl font-bold text-green-600">₹{totalEarnings.toLocaleString()}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="shadow-card">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 rounded-lg bg-orange-100">
                    <Clock className="h-6 w-6 text-orange-600" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Pending Amount</p>
                    <p className="text-2xl font-bold text-orange-600">₹{totalPending.toLocaleString()}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="shadow-card">
              <CardContent className="p-6">
                <div className="flex items-center gap-4">
                  <div className="p-3 rounded-lg bg-blue-100">
                    <Calendar className="h-6 w-6 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Months Paid</p>
                    <p className="text-2xl font-bold">{paidMonths} / 12</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Year Filter */}
          <Card>
            <CardContent className="p-4">
              <div className="flex items-center gap-4">
                <span className="text-sm font-medium">Select Year:</span>
                <Select value={String(selectedYear)} onValueChange={(v) => setSelectedYear(parseInt(v))}>
                  <SelectTrigger className="w-32">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {[2024, 2025, 2026].map(y => (
                      <SelectItem key={y} value={String(y)}>{y}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          {/* Payroll Table */}
          <Card className="shadow-card">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <CreditCard className="h-5 w-5" />
                Salary Records - {selectedYear}
              </CardTitle>
              <CardDescription>Your monthly salary records and payslips</CardDescription>
            </CardHeader>
            <CardContent>
              {payroll.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">
                  No payroll records found for {selectedYear}
                </div>
              ) : (
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Month</TableHead>
                      <TableHead>Basic</TableHead>
                      <TableHead>Allowances</TableHead>
                      <TableHead>Deductions</TableHead>
                      <TableHead>Net Salary</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Paid On</TableHead>
                      <TableHead className="text-right">Action</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {payroll.map((record) => (
                      <TableRow key={record.id}>
                        <TableCell className="font-medium">{MONTHS[record.month - 1]}</TableCell>
                        <TableCell>₹{record.basic_salary.toLocaleString()}</TableCell>
                        <TableCell className="text-green-600">+₹{record.allowances.toLocaleString()}</TableCell>
                        <TableCell className="text-red-600">-₹{record.deductions.toLocaleString()}</TableCell>
                        <TableCell className="font-semibold">₹{record.net_salary.toLocaleString()}</TableCell>
                        <TableCell>
                          <Badge variant={record.status === "paid" ? "default" : "secondary"}>
                            {record.status === "paid" ? "Paid" : "Pending"}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          {record.paid_at ? format(new Date(record.paid_at), "dd MMM") : "-"}
                        </TableCell>
                        <TableCell className="text-right">
                          {record.status === "paid" && (
                            <Button 
                              variant="outline" 
                              size="sm" 
                              onClick={() => handleDownloadPayslip(record)}
                            >
                              <Download className="h-4 w-4 mr-1" />
                              Payslip
                            </Button>
                          )}
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              )}
            </CardContent>
          </Card>

          {/* Bank Details */}
          {teacherData?.employees && (
            <Card className="shadow-card">
              <CardHeader>
                <CardTitle>Bank Details</CardTitle>
                <CardDescription>Your salary account information</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground">Bank Name</p>
                    <p className="font-medium">{teacherData.employees.bank_name || "Not provided"}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Account Number</p>
                    <p className="font-medium">{teacherData.employees.bank_account || "Not provided"}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Employee Code</p>
                    <p className="font-medium">{teacherData.employees.employee_code || "Not assigned"}</p>
                  </div>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </DashboardLayout>
    </>
  );
};

export default TeacherPayroll;